[build]
builder = "DOCKERFILE"
dockerfilePath = "api-video-processor/Dockerfile"
rootDirectory = "api-video-processor"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port 3001"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
